//
//  Constants.h
//  ImgProc
//
//  Created by Jamis Johnson on 2/23/12.
//  Copyright (c) 2012 University of Utah. All rights reserved.
//

#import <Foundation/Foundation.h>


// SCROLLVIEW
extern const CGRect PHOTOVIEW_FRAME;

// ALGORITHM VIEW
#define ALGORITHM_VIEW_HEIGHT   45.0

// SCROLLVIEW
#define SCROLLVIEW_HEIGHT       94.0
#define SCROLLVIEW_SPACE_BETWEEN_BUTTONS    16

// ALGORITHMS
#define NUM_ALGORITHMS          14

// keeps track of what algorithm the user is in
#define ALGORITHM_NONE                  0
#define ALGORITHM_INVERT                1
#define ALGORITHM_CONTRAST              2
#define ALGORITHM_BRIGHTNESS            3
#define ALGORITHM_THRESHOLD             4
#define ALGORITHM_GAMMA                 5
#define ALGORITHM_GRADIENT_MAGNITUDE    6
#define ALGORITHM_FAST_EDGES            7
#define ALGORITHM_GAUSSIAN_BLUR         8
#define ALGORITHM_FAST_SHARPEN          9
#define ALGORITHM_DEMO                  10

// initial, maximum and minimum values for each algorithm
#define ALGORITHM_INIT_VAL_CONTRAST     2
#define ALGORITHM_MAX_VAL_CONTRAST      30
#define ALGORITHM_MIN_VAL_CONTRAST      1
#define ALGORITHM_FINGER_MOVEMENT_SCALE_CONTRAST  8.0

#define ALGORITHM_INIT_VAL_BRIGHTNESS   55
#define ALGORITHM_MAX_VAL_BRIGHTNESS    255
#define ALGORITHM_MIN_VAL_BRIGHTNESS    0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_BRIGHTNESS  1.0

#define ALGORITHM_INIT_VAL_THRESHOLD    115
#define ALGORITHM_MAX_VAL_THRESHOLD     255
#define ALGORITHM_MIN_VAL_THRESHOLD     0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_THRESHOLD  1.0

#define ALGORITHM_INIT_VAL_GAMMA        3
#define ALGORITHM_MAX_VAL_GAMMA         255
#define ALGORITHM_MIN_VAL_GAMMA         0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_GAMMA  1.0

#define ALGORITHM_INIT_VAL_GRADIENT_MAGNITUDE   3.0
#define ALGORITHM_MAX_VAL_GRADIENT_MAGNITUDE    255.0
#define ALGORITHM_MIN_VAL_GRADIENT_MAGNITUDE    0.0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_GRADIENT_MAGNITUDE  1.0

#define ALGORITHM_INIT_VAL_FAST_EDGES   125 //5
#define ALGORITHM_MAX_VAL_FAST_EDGES    255 //23
#define ALGORITHM_MIN_VAL_FAST_EDGES    0 //1
#define ALGORITHM_FINGER_MOVEMENT_SCALE_FAST_EDGES  12.0

#define ALGORITHM_INIT_VAL_GAUSSIAN_BLUR    4
#define ALGORITHM_MAX_VAL_GAUSSIAN_BLUR     255
#define ALGORITHM_MIN_VAL_GAUSSIAN_BLUR     0
#define ALGORITHM_FINGER_MOVEMENT_GAUSSIAN_BLUR  1.0

/*
#define ALGORITHM_INIT_VAL_FAST_SHARPEN     3
#define ALGORITHM_MAX_VAL_FAST_SHARPEN      255
#define ALGORITHM_MIN_VAL_FAST_SHARPEN      0
 #define ALGORITHM_FINGER_MOVEMENT_SCALE_FAST_SHARPEN  8.0
 */


// LIVE VIDEO
#define LIVE_VIDEO_FRAMES_PER_SECOND    25

// CAMERA (PICTURES)
#define PHOTOVIEW_REAR_CAMERA_SCALE     3.0
#define PHOTOVIEW_FRONT_CAMERA_SCALE    1.0