//
//  Constants.h
//  ImgProc
//
//  Created by Jamis Johnson on 2/23/12.
//  Copyright (c) 2012 University of Utah. All rights reserved.
//

#import <Foundation/Foundation.h>

extern const CGRect PHOTOVIEW_FRAME;

// FRAMES
// IPHONE
// ALGORITHM-VIEW FRAMES
extern const CGRect FRAME_ALGORITHMS_VIEW_IPHONE_SCROLL_VIEW;
extern const CGRect FRAME_ALGORITHMS_VIEW_IPHONE_ALGORITHM_CONTROLS;
extern const CGRect FRAME_ALGORITHMS_VIEW_IPHONE_NAV_BAR;
// MAIN-VIEW FRAMES
extern const CGRect FRAME_MAIN_VIEW_IPHONE_SCROLL_VIEW;
extern const CGRect FRAME_MAIN_VIEW_IPHONE_ALGORITHM_CONTROLS;
extern const CGRect FRAME_MAIN_VIEW_IPHONE_NAV_BAR;
// IPAD
// ALGORITHM-VIEW FRAMES
extern const CGRect FRAME_ALGORITHMS_VIEW_IPAD_SCROLL_VIEW;
extern const CGRect FRAME_ALGORITHMS_VIEW_IPAD_ALGORITHM_CONTROLS;
extern const CGRect FRAME_ALGORITHMS_VIEW_IPAD_NAV_BAR;
// MAIN-VIEW FRAMES
extern const CGRect FRAME_MAIN_VIEW_IPAD_SCROLL_VIEW;
extern const CGRect FRAME_MAIN_VIEW_IPAD_ALGORITHM_CONTROLS;
extern const CGRect FRAME_MAIN_VIEW_IPAD_NAV_BAR;

// VIEW DIMENSIONS - IPHONE
#define ALGORITHM_VIEW_HEIGHT   45.0
#define ALGORITHM_VIEW_HEIGHT_IPAD  80.0
#define SCROLLVIEW_HEIGHT       96.0
#define SCROLLVIEW_HEIGHT_IPAD  174.0
#define SCROLLVIEW_WIDTH_IPHONE       320.0
#define SCROLLVIEW_SPACE_BETWEEN_BUTTONS    13
#define SCROLLVIEW_SPACE_BETWEEN_BUTTONS_IPAD    20

// VIEW DIMENSIONS - IPAD

// ALGORITHMS
#define NUM_ALGORITHMS          18

// keeps track of what algorithm the user is in
#define ALGORITHM_NONE                  0
#define ALGORITHM_DEMO                  1
#define ALGORITHM_INVERT                2
#define ALGORITHM_CONTRAST              3
#define ALGORITHM_BRIGHTNESS            4
#define ALGORITHM_THRESHOLD             5
#define ALGORITHM_GAMMA                 6
#define ALGORITHM_GRADIENT_MAGNITUDE    7
#define ALGORITHM_FAST_EDGES            8
#define ALGORITHM_SOBEL_EDGES           9
#define ALGORITHM_GAUSSIAN_BLUR         10
#define ALGORITHM_FAST_SHARPEN          11
#define ALGORITHM_CARTOON               12
#define ALGORITHM_POSTERIZE             13
#define ALGORITHM_SKETCH                14
#define ALGORITHM_STATIC                15
#define ALGORITHM_ERODE                 16
#define ALGORITHM_DILATE                17
#define ALGORITHM_NOISE_REDUCTION       18

// initial, maximum and minimum values for each algorithm
#define ALGORITHM_INIT_VAL_CONTRAST     2
#define ALGORITHM_MAX_VAL_CONTRAST      30
#define ALGORITHM_MIN_VAL_CONTRAST      1
#define ALGORITHM_FINGER_MOVEMENT_SCALE_CONTRAST  8.0

#define ALGORITHM_INIT_VAL_BRIGHTNESS   55
#define ALGORITHM_MAX_VAL_BRIGHTNESS    255
#define ALGORITHM_MIN_VAL_BRIGHTNESS    0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_BRIGHTNESS  1.0

#define ALGORITHM_INIT_VAL_THRESHOLD    115
#define ALGORITHM_MAX_VAL_THRESHOLD     255
#define ALGORITHM_MIN_VAL_THRESHOLD     0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_THRESHOLD  1.0

#define ALGORITHM_INIT_VAL_GAMMA        3.0
#define ALGORITHM_MAX_VAL_GAMMA         90.0
#define ALGORITHM_MIN_VAL_GAMMA         1.0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_GAMMA  1.0

#define ALGORITHM_INIT_VAL_GRADIENT_MAGNITUDE   3.0
#define ALGORITHM_MAX_VAL_GRADIENT_MAGNITUDE    255.0
#define ALGORITHM_MIN_VAL_GRADIENT_MAGNITUDE    0.0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_GRADIENT_MAGNITUDE  1.0

#define ALGORITHM_INIT_VAL_FAST_EDGES   35 //5
#define ALGORITHM_MAX_VAL_FAST_EDGES    255 //23
#define ALGORITHM_MIN_VAL_FAST_EDGES    0 //1
#define ALGORITHM_FINGER_MOVEMENT_SCALE_FAST_EDGES  12.0

#define ALGORITHM_INIT_VAL_GAUSSIAN_BLUR    4.0
#define ALGORITHM_MAX_VAL_GAUSSIAN_BLUR     255.0
#define ALGORITHM_MIN_VAL_GAUSSIAN_BLUR     0.0
#define ALGORITHM_FINGER_MOVEMENT_GAUSSIAN_BLUR  1.0

/*
#define ALGORITHM_INIT_VAL_FAST_BLUR    4
#define ALGORITHM_MAX_VAL_FAST_BLUR     255
#define ALGORITHM_MIN_VAL_FAST_BLUR     0
#define ALGORITHM_FINGER_MOVEMENT_FAST_BLUR  1.0
*/

#define ALGORITHM_INIT_VAL_FAST_SHARPEN     3.0
#define ALGORITHM_MAX_VAL_FAST_SHARPEN      1.0
#define ALGORITHM_MIN_VAL_FAST_SHARPEN      0.0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_FAST_SHARPEN  1.0

#define ALGORITHM_INIT_VAL_SOBEL_EDGES     20.0
#define ALGORITHM_MAX_VAL_SOBEL_EDGES      60.0
#define ALGORITHM_MIN_VAL_SOBEL_EDGES      0.0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_SOBEL_EDGES  1.0

#define ALGORITHM_INIT_VAL_CARTOON     21
#define ALGORITHM_MAX_VAL_CARTOON      25
#define ALGORITHM_MIN_VAL_CARTOON      8
#define ALGORITHM_FINGER_MOVEMENT_SCALE_CARTOON  1.0

#define ALGORITHM_INIT_VAL_POSTERIZE     5
#define ALGORITHM_MAX_VAL_POSTERIZE      16
#define ALGORITHM_MIN_VAL_POSTERIZE      2
#define ALGORITHM_FINGER_MOVEMENT_SCALE_POSTERIZE  8.0

#define ALGORITHM_INIT_VAL_SKETCH     15
#define ALGORITHM_MAX_VAL_SKETCH      65
#define ALGORITHM_MIN_VAL_SKETCH      0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_SKETCH  1.0


/*
#define ALGORITHM_INIT_VAL_ERODE     3
#define ALGORITHM_MAX_VAL_ERODE      255
#define ALGORITHM_MIN_VAL_ERODE      0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_ERODE  1.0

#define ALGORITHM_INIT_VAL_DILATE     3
#define ALGORITHM_MAX_VAL_DILATE      255
#define ALGORITHM_MIN_VAL_DILATE      0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_DILATE  1.0

#define ALGORITHM_INIT_VAL_NOISE_REDUCTION     3
#define ALGORITHM_MAX_VAL_NOISE_REDUCTION      255
#define ALGORITHM_MIN_VAL_NOISE_REDUCTION      0
#define ALGORITHM_FINGER_MOVEMENT_SCALE_NOISE_REDUCTION  1.0
*/


// LIVE VIDEO
#define LIVE_VIDEO_FRAMES_PER_SECOND    25

// CAMERA (PICTURES)
#define PHOTOVIEW_REAR_CAMERA_SCALE     3.0
#define PHOTOVIEW_FRONT_CAMERA_SCALE    1.0
#define PHOTOVIEW_ORIGINAL_IMAGE_SCALE  1.3

